-- ==================================================================
-- CREATE TABLE: APP_DATA_OWNER.APP_CACHE_NEW
-- ==================================================================
-- Generated: 2025-10-25 16:33:49
-- Migration Action: add_interval_hash_partitioning
-- Source Table: APP_DATA_OWNER.APP_CACHE-- Current: Non-partitioned table-- Target Partitioning: INTERVAL-HASH-- ==================================================================

SET ECHO ON
SET SERVEROUTPUT ON
SET TIMING ON
SET FEEDBACK ON

PROMPT ================================================================
PROMPT Step 10: Creating New Partitioned Table
PROMPT ================================================================
PROMPT Table: APP_DATA_OWNER.APP_CACHE_NEW
PROMPT Partitioning: INTERVAL (MONTH)PROMPT Partition Column: EXPIRY_TIME
PROMPT Subpartitioning: HASH on CACHE_KEYPROMPT Hash Subpartitions: 8PROMPT Tablespace: USERS
PROMPT LOB Columns: 2
PROMPT ================================================================

-- Check if table already exists (generic)
@validation/check_table_exists.sql APP_DATA_OWNER APP_CACHE_NEW

-- Create new table with partitioning
PROMPT

PROMPT Creating table APP_DATA_OWNER.APP_CACHE_NEW...
PROMPT Estimated time: < 1 minute



CREATE TABLE "APP_DATA_OWNER"."APP_CACHE_NEW"
(    CACHE_KEY VARCHAR2(200) NOT NULL,    CACHE_VALUE BLOB,    CACHE_METADATA BLOB,    EXPIRY_TIME TIMESTAMP(6))TABLESPACE USERSPCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
    INITIAL 65536
    NEXT 1048576
    BUFFER_POOL DEFAULT
)-- Partition the main table data by date, and subpartition by hash
PARTITION BY RANGE (EXPIRY_TIME)
INTERVAL (INTERVAL '1' MONTH) -- Create a new partition for each monthSUBPARTITION BY HASH (CACHE_KEY) SUBPARTITIONS 8 -- Create 8 hash subpartitions per interval partition(
    -- Define the initial, pre-interval partition
    PARTITION p_before_2024_01_01 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD'))    (        SUBPARTITION p_before_2024_01_01_s1 TABLESPACE USERS            LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_01),            LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_01),        SUBPARTITION p_before_2024_01_01_s2 TABLESPACE USERS            LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_02),            LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_02),        SUBPARTITION p_before_2024_01_01_s3 TABLESPACE USERS            LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_03),            LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_03),        SUBPARTITION p_before_2024_01_01_s4 TABLESPACE USERS            LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_04),            LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_04),        SUBPARTITION p_before_2024_01_01_s5 TABLESPACE USERS            LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_01),            LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_01),        SUBPARTITION p_before_2024_01_01_s6 TABLESPACE USERS            LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_02),            LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_02),        SUBPARTITION p_before_2024_01_01_s7 TABLESPACE USERS            LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_03),            LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_03),        SUBPARTITION p_before_2024_01_01_s8 TABLESPACE USERS            LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_04),            LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_04)    ))-- Subpartition template for all future interval partitions
SUBPARTITION TEMPLATE (    SUBPARTITION s1 TABLESPACE USERS        LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_01),        LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_01),    SUBPARTITION s2 TABLESPACE USERS        LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_02),        LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_02),    SUBPARTITION s3 TABLESPACE USERS        LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_03),        LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_03),    SUBPARTITION s4 TABLESPACE USERS        LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_04),        LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_04),    SUBPARTITION s5 TABLESPACE USERS        LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_01),        LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_01),    SUBPARTITION s6 TABLESPACE USERS        LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_02),        LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_02),    SUBPARTITION s7 TABLESPACE USERS        LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_03),        LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_03),    SUBPARTITION s8 TABLESPACE USERS        LOB (CACHE_METADATA) STORE AS SECUREFILE (TABLESPACE GD_LOB_04),        LOB (CACHE_VALUE) STORE AS SECUREFILE (TABLESPACE GD_LOB_04))ENABLE ROW MOVEMENT;

PROMPT ✓ Table APP_DATA_OWNER.APP_CACHE_NEW created successfully


-- Post-create table checks (structure, partitioning, LOBs, stats)
@validation/post_create_table_checks.sql APP_DATA_OWNER APP_CACHE_NEW 4

PROMPT
PROMPT ================================================================
PROMPT Step 10 Complete: Table Structure Created
PROMPT ================================================================
PROMPT Status: SUCCESS
PROMPT Table: APP_DATA_OWNER.APP_CACHE_NEWPROMPT Partitioning: INTERVAL-HASHPROMPT
PROMPT Next Steps:
PROMPT   1. Review table structure above
PROMPT   2. Run 20_data_load.sql to load data (est. < 1 minute)
PROMPT   3. Monitor space and performance
PROMPT ================================================================