-- ==================================================================
-- CREATE TABLE: APP_DATA_OWNER.TEMP_CALCULATIONS_NEW
-- ==================================================================
-- Generated: 2025-10-25 16:33:49
-- Migration Action: add_interval_hash_partitioning
-- Source Table: APP_DATA_OWNER.TEMP_CALCULATIONS-- Current: Non-partitioned table-- Target Partitioning: INTERVAL-HASH-- ==================================================================

SET ECHO ON
SET SERVEROUTPUT ON
SET TIMING ON
SET FEEDBACK ON

PROMPT ================================================================
PROMPT Step 10: Creating New Partitioned Table
PROMPT ================================================================
PROMPT Table: APP_DATA_OWNER.TEMP_CALCULATIONS_NEW
PROMPT Partitioning: INTERVAL (MONTH)PROMPT Partition Column: CALC_TIMESTAMP
PROMPT Subpartitioning: HASH on CALC_IDPROMPT Hash Subpartitions: 8PROMPT Tablespace: USERS
PROMPT ================================================================

-- Check if table already exists (generic)
@validation/check_table_exists.sql APP_DATA_OWNER TEMP_CALCULATIONS_NEW

-- Create new table with partitioning
PROMPT

PROMPT Creating table APP_DATA_OWNER.TEMP_CALCULATIONS_NEW...
PROMPT Estimated time: < 1 minute



CREATE TABLE "APP_DATA_OWNER"."TEMP_CALCULATIONS_NEW"
(    CALC_ID NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 21 INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20 NOCYCLE NOORDER) NOT NULL,    CALC_NAME VARCHAR2(100),    INPUT_VALUE NUMBER,    OUTPUT_VALUE NUMBER,    CALC_TIMESTAMP TIMESTAMP(6) DEFAULT SYSTIMESTAMP)TABLESPACE USERSPCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (
    INITIAL 65536
    NEXT 1048576
    BUFFER_POOL DEFAULT
)-- Partition the main table data by date, and subpartition by hash
PARTITION BY RANGE (CALC_TIMESTAMP)
INTERVAL (INTERVAL '1' MONTH) -- Create a new partition for each monthSUBPARTITION BY HASH (CALC_ID) SUBPARTITIONS 8 -- Create 8 hash subpartitions per interval partition(
    -- Define the initial, pre-interval partition
    PARTITION p_before_2024_01_01 VALUES LESS THAN (TO_DATE('2024-01-01', 'YYYY-MM-DD')))ENABLE ROW MOVEMENT;

PROMPT ✓ Table APP_DATA_OWNER.TEMP_CALCULATIONS_NEW created successfully


-- Post-create table checks (structure, partitioning, LOBs, stats)
@validation/post_create_table_checks.sql APP_DATA_OWNER TEMP_CALCULATIONS_NEW 4

PROMPT
PROMPT ================================================================
PROMPT Step 10 Complete: Table Structure Created
PROMPT ================================================================
PROMPT Status: SUCCESS
PROMPT Table: APP_DATA_OWNER.TEMP_CALCULATIONS_NEWPROMPT Partitioning: INTERVAL-HASHPROMPT
PROMPT Next Steps:
PROMPT   1. Review table structure above
PROMPT   2. Run 20_data_load.sql to load data (est. < 1 minute)
PROMPT   3. Monitor space and performance
PROMPT ================================================================