# Oracle Database Configuration
# This file contains database connection and testing configuration

database:
  # Connection settings
  host: localhost
  port: 1521
  service_name: XE
  username: system
  password: ${ORACLE_PASSWORD:-OraclePassword123}
  
  # Connection pool settings
  pool:
    min_connections: 2
    max_connections: 10
    timeout: 30
  
  # Testing settings
  testing:
    timeout: 300
    retry_attempts: 3
    cleanup_after_test: true
    
  # Security settings
  security:
    enable_audit: true
    encrypt_connections: true
    require_ssl: false

# Oracle versions to test
oracle_versions:
  - 19-slim
  - 21-slim
  - 23-slim

# Test categories
test_categories:
  - basic
  - integration
  - performance
  - security
