version: '3.8'

services:
  # Oracle Database XE 21c - Optimized for Performance Testing
  oracle:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-test-db
    environment:
      # System password
      ORACLE_PASSWORD: Oracle123!
      
      # Create HR schema automatically
      APP_USER: hr
      APP_USER_PASSWORD: hr123
      
      # Create HR_APP schema via init script
      ORACLE_DATABASE: XEPDB1
      
      # Oracle Performance Tuning
      ORACLE_CHARACTERSET: AL32UTF8
      ENABLE_ARCHIVELOG: false
    
    ports:
      - "1521:1521"
      - "5500:5500"
    
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-scripts:/docker-entrypoint-initdb.d/startup
    
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s
    
    # Resource limits optimized for largest Codespace (32-core, 64GB RAM)
    # Allocate significant resources to Oracle for performance testing
    deploy:
      resources:
        limits:
          cpus: '16'
          memory: 32G
        reservations:
          cpus: '8'
          memory: 16G
    
    # Shared memory for Oracle SGA - critical for performance
    shm_size: 8gb
    
    # Use tmpfs for better I/O performance on temp data
    tmpfs:
      - /dev/shm:rw,noexec,nosuid,size=8g
    
    networks:
      - oracle-network

  # Workspace container - Optimized for development
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: workspace
    
    volumes:
      - ..:/workspace:cached
    
    command: sleep infinity
    
    depends_on:
      oracle:
        condition: service_healthy
    
    # Resource allocation for workspace
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
    
    environment:
      ORACLE_HOST: oracle
      ORACLE_PORT: 1521
      ORACLE_SERVICE: XEPDB1
      ORACLE_USER: hr
      ORACLE_PASSWORD: hr123
      ORACLE_SYS_PASSWORD: Oracle123!
      TNS_ADMIN: /workspace/table_migration/wallets
      
      # Python optimization for performance
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      
      # Oracle client configuration
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
      ORA_SDTZ: UTC
    
    networks:
      - oracle-network

volumes:
  oracle-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/oracle-data

networks:
  oracle-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
